In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Export_Output.txt", sep=";")

In [3]:
data.head()

,NAME,COUNTRY,ISO_CODE,ISO_CC,ADMINTYPE,COUNTRYAFF,CONTINENT,LAND_TYPE,Confirmed,Deaths,x,y,ObjectId
0,Jersey,Jersey,JE,JE,Crown Dependency,United Kingdom,Europe,Small island,"108,000000000000000","2,000000000000000","-2,132803928000000","49,213757409999999",1
1,Vysocina,Czech Republic,https://onemocneni-aktualne.mzcr.cz/covid-19,CZ,Region,Czech Republic,Europe,Primary land,"108,000000000000000","0,000000000000000","15,671885280000000","49,414965010000003",2
2,Kanagawa,Japan,https://www3.nhk.or.jp/news/html/20200304/k100...,JP,Prefecture,Japan,Asia,Primary land,"107,000000000000000","5,000000000000000","139,332908800000010","35,416575840000000",3
3,Nei Mongol,China,https://3g.dxy.cn/newh5/view/pneumonia?scene=2...,CN,Autonomous Region,China,Asia,Primary land,"107,000000000000000","1,000000000000000","114,227568300000000","44,455733780000003",4
4,Herat,Afghanistan,https://ariananews.af/two-new-covid-19-cases-t...,AF,Province,Afghanistan,Asia,Primary land,"106,000000000000000","3,000000000000000","62,130837849999999","34,187415590000001",5

In [5]:
data.to_csv("Alert1.csv", index=False)

In [6]:
data = pd.read_csv("Alert1.csv")

In [7]:
data.head()

,NAME,COUNTRY,ISO_CODE,ISO_CC,ADMINTYPE,COUNTRYAFF,CONTINENT,LAND_TYPE,Confirmed,Deaths,x,y,ObjectId
0,Jersey,Jersey,JE,JE,Crown Dependency,United Kingdom,Europe,Small island,"108,000000000000000","2,000000000000000","-2,132803928000000","49,213757409999999",1
1,Vysocina,Czech Republic,https://onemocneni-aktualne.mzcr.cz/covid-19,CZ,Region,Czech Republic,Europe,Primary land,"108,000000000000000","0,000000000000000","15,671885280000000","49,414965010000003",2
2,Kanagawa,Japan,https://www3.nhk.or.jp/news/html/20200304/k100...,JP,Prefecture,Japan,Asia,Primary land,"107,000000000000000","5,000000000000000","139,332908800000010","35,416575840000000",3
3,Nei Mongol,China,https://3g.dxy.cn/newh5/view/pneumonia?scene=2...,CN,Autonomous Region,China,Asia,Primary land,"107,000000000000000","1,000000000000000","114,227568300000000","44,455733780000003",4
4,Herat,Afghanistan,https://ariananews.af/two-new-covid-19-cases-t...,AF,Province,Afghanistan,Asia,Primary land,"106,000000000000000","3,000000000000000","62,130837849999999","34,187415590000001",5

In [ ]:
data[data["COUNTRY"]]